{{- if .Values.configmap}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
data: {{- toYaml .Values.configmap | nindent 2 }}
{{- end }}