
{{- if .Values.secret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
type: Opaque
stringData: {{- toYaml .Values.secret | nindent 2 }}
{{- end }}