# Creates a service account - should probably be created somewhere else.
{{- if .Values.serviceAccount}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "Missing .Values.replicaCount" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
{{- end}}
{{- end}}
